services:
  test:
    build:
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
     networks:
      - testlan
    command: ["lb", "--trace=true"]

networks:
  testlan:
    internal: true
    enable_ipv6: @ENABLE_IPv6@
    ipam:
      config:
        - subnet: @CURRENT_NET@
