networks:
  servers:

services:

  balancer:
    build: .
    command: lb
    networks:
      - servers
    ports:
      - 8090:8090

  server1:
    build: .
    networks:
      - servers
    expose:
      - 8080

  server2:
    build: .
    networks:
      - servers
    expose:
      - 8080

  server3:
    build: .
    networks:
      - servers
    expose:
      - 8080