services:
  test:
    build:
      dockerfile: test.dockerfile
    networks:
      - testlan
    depends_on:
      - server1
      - server2
      - server3
      - balancer
    cap_add:
      - NET_ADMIN
    environment:
      - CURRENT_NET=@CURRENT_NET@
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  balancer:
    networks:
      - testlan
    command: ["lb", "--trace=true"]

networks:
  testlan:
    enable_ipv6: @ENABLE_IPv6@
    ipam:
      config:
        - subnet: @CURRENT_NET@
